version: '3.9'

services:
  notifyrs:
    image: fidoriel/notifyrs:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SENDER_EMAIL=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - DEFAULT_RECIPIENT_EMAILS=
      - SMTP_HOST=
      #- SECRET_KEY=1234567890